config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'loans#index'
  resources :loans
  namespace :admin do
    get 'panel' => 'admin/loans#index'
    resources :loans do 
      member do 
        patch :approve
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  scope :approved, -> { where(approved: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :loans
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'
end

app/controllers/admin/loans_controller.rb
class Admin::LoansController < Admin::AdminController
  def index
    @loans = Loan.includes(:user)
  end

  def approve
    loan = Loan.find_by_id(params['id'])
    loan.approved = !loan.approved
    loan.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def index
    @loans = current_user.loans
  end

  def new
    @loan = Loan.new
  end

  def create
    @loan = current_user.loans.new(loan_params)

    @loan.credit_score = ::CreditScore.new(current_user).score
    @loan.credit_limit = ::CheckEligibility.new(@loan).call

    respond_to do |format|
      if @loan.save!
        format.html { redirect_to loans_path, notice: 'Credit card appllication submitted successfully' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def loan_params
    params.require(:loan).permit(:email, :pan_card, :aadhar_number, :bank_account_number, :bank_ifsc,
                                 :monthly_recurring_inflow, :monthly_recurring_outflow)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/loans/index.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
  
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
<div class="card">
  <div class="card-header">
    Credit Card Applications
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-lg-12">
      <table id="example" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Email</th>
                <th>Credit Limit</th>
                <th>System Recommendation</th>
            </tr>
        </thead>
        <tbody>
          <% @loans.each do |loan|%>
            <tr>
                <td><%=loan.user.email%></td>
                <td><%=loan.credit_limit%></td>
                <td>
                
                <%if loan.credit_score > 2 %>
                  <%=check_box_tag 'approved', true, loan.approved,
                    onchange: "$(this).data('params', 'approved=' + this.checked)",
                    data: { remote: true, url: approve_admin_loan_path(id: loan.id), method: :patch }
                  %> 
                  <% if loan.approved %>
                    Approved
                  <%else%>
                    Approve
                  <%end%>
                <%else%>
                  Reject
                <%end%>
              </td>
            </tr>
          <%end%>
          </tbody>
    </table>      
    </div>
    </div>
  </div>
<script>
$(document).ready( function () {
    $('#example').DataTable();
} );
</script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Panagea - Premium site template for travel agencies, hotels and restaurant listing.">
    <meta name="author" content="Ansonika">
    <title>Credit Card App</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>
  <body class="fixed-nav sticky-footer" id="page-top">
    <%= render "shared/navbar" %>
    <%# <%= render "shared/sidebar" %>
    <div class="content-wrapper">
      <div class="container-fluid">
        <% flash.each do |type, msg| %>
          <p class="alert bg-danger">
            <%= msg %>
          </p>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Credit card App</title>
  <%=csrf_meta_tags%>
  <meta name="description" content="<%= @page_description %>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <% unless current_user&.admin%>
    <%= render 'shared/nav' %>
  <%else%>
  <%= render 'shared/navbar' %>
  <%end%>
</head>
<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

  <%= yield %>
</body>
</html

app/views/loans/_form.html.erb
<div class="card">
  <div class="card-header">
    Credit Card Application Form
  </div>
  <div class="card-body">
      <div class="row">
        <div class="col-lg-6">
            <%#= form_for :loan, class: "signupForm" do |f| %>
          <%= form_for(@loan) do |f| %>         
            <div class="form-group">
            <label for="exampleFormControlInput1">Email address</label>
              <%= f.text_field :email, class: "form-control" %> <br />
            </div>
            <div class="form-group">
            <label for="exampleFormControlInput1">Pan Number</label>
              <%= f.text_field :pan_card, class: "form-control" %> <br />
            </div>
            <div class="form-group">
            <label for="exampleFormControlInput1">Aadhar Number</label>
              <%= f.text_field :aadhar_number, class: "form-control" %> <br />
            </div>
            <div class="form-group">
            <label for="exampleFormControlInput1">Bank Account Number</label>
              <%= f.text_field :bank_account_number, class: "form-control" %> <br />
            </div>
            <div class="form-group">
            <label for="exampleFormControlInput1">Bank Account IFSC</label>
              <%= f.text_field :bank_ifsc, class: "form-control" %> <br />
            </div>
            <div class="form-group">
            <label for="exampleFormControlInput1">Monthly Recurring Inflow</label>
              <%= f.text_field :monthly_recurring_inflow, class: "form-control" %> <br />
            </div>
            <div class="form-group">
            <label for="exampleFormControlInput1">Monthly Recurring Outflow</label>
              <%= f.text_field :monthly_recurring_outflow, class: "form-control" %> <br />
            </div>
              <%= f.submit "Submit Loan Application", class: "button createAccount" %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/loans/index.html.erb
<% name = current_user.present? ? current_user.email : 'Stranger' %>

app/views/loans/new.html.erb
<%= render 'form'%>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Loan App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li>
               <%= link_to 'New Loan', new_loan_path, class: 'nav-link' %>

            </li>
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Loans Dashboard', admin_loans_path, class: 'nav-link' %>
        </li>
      </ul>
      <!-- Left links -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
  </div>
</div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

app/views/shared/_sidebar.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Simple Sidebar - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <%= stylesheet_link_tag "admin" %>
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">Start Bootstrap</div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Dashboard</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Shortcuts</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Overview</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Events</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Profile</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Status</a>
                </div>
            </div>
            <!-- Page content wrapper-->
            
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
    </body>
</html>